# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Pizza

pool:
  vmImage: 'ubuntu-latest'

variables:
  appDir: Pizza

steps:
- checkout: self
  clean: true
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDir)


- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud analysis
  inputs:
    SonarCloud: 'SonarCloudService'
    organization: '1909-sep30-net'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Project2JAGV-Angular'
    cliSources: '$(appDir)/src'
    extraProperties: |
      sonar.coverage.exclusions=**/*.spec.ts
      sonar.typescript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info

- script: npx ng build --prod
  displayName: ng build
  workingDirectory: $(appDir)

- script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
  displayName: ng test
  workingDirectory: $(appDir)

- script: npm run lint
  displayName: ng lint
  workingDirectory: $(appDir)

- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(6)(1aea89d4-388d-4d50-938f-9c95f509c96d)'
    appType: 'webApp'
    WebAppName: 'angpizza'
    packageForLinux: '$(appDir)/dist/*'
